version: '3.1'

services:

  mysql:
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass.123
      MYSQL_DATABASE: test